server:
    port: 8081

spring:
    security:
        oauth2:
            client:
                registration:
                    keycloak:
                        clientId: oauth2-client-app
                        clientSecret: tynI8eYUw4H1fJYxwLQ36XhFC1Ge1w1x
                        clientName: oauth2-client-app
                        authorizationGrantType: authorization_code
                        scope: openid,profile
                        clientAuthenticationMethod: client_secret_basic
                        redirectUri: http://localhost:8081/login/oauth2/code/keycloak

                provider:
                    keycloak:
                        issuerUri: http://localhost:8080/realms/oauth2
                        authorizationUri: http://localhost:8080/realms/oauth2/protocol/openid-connect/auth
                        jwkSetUri: http://localhost:8080/realms/oauth2/protocol/openid-connect/certs
                        tokenUri: http://localhost:8080/realms/oauth2/protocol/openid-connect/token
                        userInfoUri: http://localhost:8080/realms/oauth2/protocol/openid-connect/userinfo
                        userNameAttribute: preferred_username

